spring:
  application:
    name: appointment-booking-service
  
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:appointment_db}
    username: ${DB_USERNAME:postgres}
    password: ${DB_PASSWORD:postgres}
    hikari:
      maximum-pool-size: ${DB_POOL_SIZE:10}
      minimum-idle: ${DB_MIN_IDLE:5}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: ${FORMAT_SQL:false}
        jdbc:
          time_zone: UTC
    show-sql: ${SHOW_SQL:false}
  
  flyway:
    enabled: ${FLYWAY_ENABLED:true}
    baseline-on-migrate: ${FLYWAY_BASELINE_ON_MIGRATE:true}
    locations: classpath:db/migration
    clean-disabled: ${FLYWAY_CLEAN_DISABLED:true}
  
  jackson:
    date-format: com.fasterxml.jackson.databind.util.StdDateFormat
    default-property-inclusion: non_null
    serialization:
      write-dates-as-timestamps: false
    deserialization:
      adjust-dates-to-context-time-zone: false
      fail-on-unknown-properties: false
  
  security:
    oauth2:
      resourceserver:
        jwt:
          jwk-set-uri: ${KEYCLOAK_URL:http://localhost:8081/auth}/realms/${KEYCLOAK_REALM:appointment-realm}/protocol/openid-connect/certs

# Server configuration
server:
  port: ${PORT:8081}
  servlet:
    context-path: /api
  error:
    include-message: always
    include-binding-errors: always
    include-stacktrace: ${INCLUDE_STACKTRACE:never}
  tomcat:
    max-threads: ${TOMCAT_MAX_THREADS:200}
    min-spare-threads: ${TOMCAT_MIN_SPARE_THREADS:20}

# Logging configuration
logging:
  level:
    root: ${LOG_LEVEL_ROOT:INFO}
    com.dominikdev: ${LOG_LEVEL_APP:DEBUG}
    org.springframework.web: ${LOG_LEVEL_SPRING_WEB:INFO}
    org.springframework.security: ${LOG_LEVEL_SPRING_SECURITY:TRACE}
    org.springframework.transaction: ${LOG_LEVEL_SPRING_TX:INFO}
    org.hibernate: ${LOG_LEVEL_HIBERNATE:INFO}
    org.hibernate.SQL: ${LOG_LEVEL_HIBERNATE_SQL:INFO}
    org.hibernate.type.descriptor.sql.BasicBinder: ${LOG_LEVEL_HIBERNATE_PARAMS:INFO}
#  file:
#    name: ${LOG_FILE_PATH:/var/log/appointment-service/application.log}

# Keycloak Configuration
keycloak:
  enabled: ${KEYCLOAK_ENABLED:true}
  realm: ${KEYCLOAK_REALM:appointment-realm}
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080}
  resource: ${KEYCLOAK_CLIENT_ID:appointment-client}
  public-client: false
  bearer-only: true
  credentials:
    secret: ${KEYCLOAK_CLIENT_SECRET:1Aq2hvKwwCqyfnDYEjzjDDzh7EkRdPLl}
  ssl-required: ${KEYCLOAK_SSL_REQUIRED:external}
  use-resource-role-mappings: true
  # Admin credentials for Keycloak Admin Client
  admin-username: ${KEYCLOAK_ADMIN_USERNAME:admin}
  admin-password: ${KEYCLOAK_ADMIN_PASSWORD:admin}
  admin-realm: ${KEYCLOAK_ADMIN_REALM:master}

# Management endpoints configuration
management:
  endpoints:
    web:
      exposure:
        include: ${ACTUATOR_ENDPOINTS:health,info,metrics,prometheus}
  endpoint:
    health:
      show-details: when_authorized
  health:
    db:
      enabled: true
  info:
    env:
      enabled: true
    build:
      enabled: true
    git:
      enabled: ${GIT_INFO_ENABLED:false}

# OpenAPI Configuration
#springdoc:
#  api-docs:
#    path: /v3/api-docs
#    enabled: ${API_DOCS_ENABLED:true}
#  swagger-ui:
#    path: /swagger-ui.html
#    disable-swagger-default-url: true
#    tags-sorter: alpha
#    operations-sorter: alpha
#  show-actuator: ${SWAGGER_SHOW_ACTUATOR:true}

# ShedLock configuration for scheduled tasks in clustered environment
#shedlock:
#  defaults:
#    lock-at-most-for: ${SHEDLOCK_DEFAULT_LOCK_AT_MOST_FOR:PT5M}
#  scheduler:
#    enabled: ${SHEDLOCK_ENABLED:true}
#    lock-at-most-for: ${SHEDLOCK_LOCK_AT_MOST_FOR:PT5M}

# Custom application settings
appointment:
  notification:
    email:
      enabled: ${EMAIL_NOTIFICATIONS_ENABLED:true}
      from-address: ${EMAIL_FROM_ADDRESS:noreply@appointment-system.com}
      template-path: ${EMAIL_TEMPLATE_PATH:templates/email/}
    sms:
      enabled: ${SMS_NOTIFICATIONS_ENABLED:true}
      from-number: ${SMS_FROM_NUMBER:+15551234567}
  security:
    admin-roles:
      - ROLE_ADMIN
      - ROLE_BUSINESS
    client-roles:
      - ROLE_CLIENT
  scheduling:
    default-slot-duration-minutes: ${DEFAULT_SLOT_DURATION:30}
    max-booking-days-in-advance: ${MAX_BOOKING_DAYS_ADVANCE:30}
    opening-hour: ${DEFAULT_OPENING_HOUR:9}
    closing-hour: ${DEFAULT_CLOSING_HOUR:17}